# Generated by Django 5.1 on 2024-09-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
