# Generated by Django 5.1 on 2024-09-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_query_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
